### ISSUE TITLE
Live Component telemetry attachment

### ISSUE THREAD

**Issue by oliver-kriska** [appsignal/appsignal-elixir-phoenix#102]
Hello,

is there special reason why you don't attach telemetry on `[:phoenix, :live_component, :update]` dispatched by Phoenix.LiveComponent? 
https://hexdocs.pm/phoenix_live_view/telemetry.html
![CleanShot 2024-11-19 at 15 37 37@2x](https://github.com/user-attachments/assets/b12bc85f-5c7f-4601-af79-35f0e066ac21)

because I don't see this even in list of attached events:
https://github.com/appsignal/appsignal-elixir-phoenix/blob/main/lib/appsignal_phoenix/live_view.ex#L53-L59

```elixir
[
      [:phoenix, :live_view, :mount],
      [:phoenix, :live_view, :handle_params],
      [:phoenix, :live_view, :handle_event],
      [:phoenix, :live_view, :render],
      [:phoenix, :live_component, :handle_event]
    ]
```

**Comment by jeffkreeftmeijer** [comment]
Hey @oliver-kriska!

Thanks for opening this issue. We don't have a specific reason why we haven't added the update message, outside of the live component message handling being a copy of the live view handling. We're careful adding new handling here, and aim to have a testing setup to make sure this won't break anything. We'll take a look to see if this is something we can add.

**Comment by oliver-kriska** [comment]
@jeffkreeftmeijer  do you have any ETA for it please?

**Comment by jeffkreeftmeijer** [comment]
I've written a patch that captures LiveComponent update events using the same mechanism as the already handled handle_event ones, thus producing a similar result. @oliver-kriska could you try the [live-component-update](https://github.com/appsignal/appsignal-elixir-phoenix/tree/live-component-update) branch to see if this matches your use case?

**Comment by oliver-kriska** [comment]
Should be ok, because I have it implemented already in our app same way.
