### ISSUE TITLE
Lisiting all of the HTTP requests under Endpoint.call/2

### ISSUE THREAD

**Issue by meysammeisam** [appsignal/appsignal-elixir-phoenix#13]
We are trying to integrate Appsignal into our umbrella! One of the services is using Phoenix.
The issue is that all of the HTTP requests are under the same category `AppsignalPhoenixExampleWeb.Endpoint.call/2`.
Is it the expected behaviour? Using the Ruby and JS clients, all of the requests are grouped by different route points(paths) which is much more convenient.
![Screenshot 2021-04-28 at 18 07 02](https://user-images.githubusercontent.com/3337117/116436425-ae4a0700-a84c-11eb-98b3-229e17e294d7.png)

The lib/packages details:
> Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.11.4 (compiled with Erlang/OTP 21)

> {:appsignal_phoenix, "~> 2.0"}
{:appsignal, "~> 2.1"}

`mix.lock`:
```elixir
  "appsignal": {:hex, :appsignal, "2.1.6", "8f2f6c12986888effdfa8abc94e37ab84635cffee5b838cdd9821c7d938503fe", [:make, :mix], [{:decorator, "~> 1.2.3 or ~> 1.3", [hex: :decorator, repo: "hexpm", optional: false]}, {:hackney, "~> 1.6", [hex: :hackney, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:poison, ">= 1.3.0", [hex: :poison, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "5db3db8e459985924255803407a1fd1440c6586dfbe8708048f846d3560392d4"},
  "appsignal_phoenix": {:hex, :appsignal_phoenix, "2.0.6", "c8c74ab4f14283cd0740bed5dc4564ddc11cbcc556e31d1d0a58e3e8f4caa695", [:mix], [{:appsignal_plug, ">= 2.0.8 and < 3.0.0", [hex: :appsignal_plug, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.4", [hex: :phoenix, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.11", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:phoenix_live_view, "~> 0.9", [hex: :phoenix_live_view, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "0c236c2770f76f2d0ca7d12ebfc0e0f161dbe107ea0247ec356ac6397dc2c7b1"},
  "appsignal_plug": {:hex, :appsignal_plug, "2.0.8", "1021f4f4039a360a2dd01163e035f1cb49ce52fc7d7edf144bfe9743e508f40c", [:mix], [{:appsignal, ">= 2.1.5 and < 3.0.0", [hex: :appsignal, repo: "hexpm", optional: false]}, {:plug, ">= 1.1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm", "fa7dbf18c5998e60b465fc4aa5de5608b2fee47b1a0ef4fa88c6659f19429074"},

```

`config/appsignal.exs`:
```elixir
config :appsignal, :config,
  otp_app: :appsignal_phoenix_example,
  name: "appsignal_phoenix_example_umbrella",
  push_api_key: "******",
  env: Mix.env
```

**Comment by shairyar** [comment]
Can you confirm:

1. if you added the appsignal dependency to each nested application inside the umbrella?
2. If you added `Appsignal.Phoenix` in your application’s endpoint file.

**Comment by meysammeisam** [comment]
@shairyar 
1. yes
2. yes, that's why we are getting requests on the app dashboard I believe!(Check the screenshot I provided above)

**Comment by shairyar** [comment]
In this case, could you enable the [transaction debug mode](https://docs.appsignal.com/elixir/configuration/options.html#option-transaction_debug_mode) config? Once enabled please visit any of the routes that are not appearing currently in AppSignal and then send us appsignal.log [file](https://docs.appsignal.com/elixir/configuration/options.html#option-log_path) at support@appsignal.com mentioning this issue.

**Comment by meysammeisam** [comment]
@shairyar Enabling the logs it turned out that the library is implemented in a way to do so! It creates a span and then names it as `AppsignalPhoenixExampleWeb.Endpoint.call/2`!
This line:
https://github.com/appsignal/appsignal-elixir-phoenix/blob/main/lib/appsignal_phoenix/event_handler.ex#L40

Here are the logs:

<img width="1591" alt="Screenshot 2021-05-03 at 16 26 12" src="https://user-images.githubusercontent.com/3337117/116889358-bf1fc180-ac2c-11eb-9a1b-697d5ef31fa0.png">

**Comment by meysammeisam** [comment]
@shairyar I opened this PR to fix it:
https://github.com/appsignal/appsignal-elixir-phoenix/pull/14

**Comment by shairyar** [comment]
Thank you, we will take a look.

**Comment by jeffkreeftmeijer** [comment]
Hey Meysam,

(I’ve posted this in #14, but I’ll quote it again here for future reference)

> The Phoenix and Plug implementation is supposed to start a root span with the controller and action name as the span’s name that should wrap the inner Endpoint.call/2 span.
> 
> If everything worked like it’s supposed to, your sample would be named YourController#index, with an inner Endpoint.call/2 span.
> 
> For some reason we’ve yet to figure out, that’s not happening in your setup. Because of that, the root span isn’t created, and the inner span is automatically treated as the root span. Usually, that’s because use Appsignal.Phoenix isn’t added to the endpoint file, but since that’s not the case for you, we’ll have to dive a bit deeper to try and reproduce your setup.
> 
> Could you contact support@appsignal.com for that? We’ll then go through your setup to build an example we can use to test on internally. We’re asking you to go through support here, as that would allow us to discuss your app without having that information end up in a public issue.

I’ll close this one, and we’ll definitely reopen it if this is a bug in the integration. Right now, we think we’ve run into something in your setup we’re not yet expecting, so let’s get that cleared up first.

Best,
-- Jeff

**Comment by meysammeisam** [comment]
> Hey Meysam,
Thanks for sharing your endpoint file. One thing I’m seeing is that you’re including Plug.Builder in your endpoint, which redefines the call/2 function we’ve overwritten with the use Appsignal.Phoenix call. From some local testing, I found that reversing those, by having Plug.Builder before Appsignal.Phoenix, resolves the issue in my setup.
﻿
﻿Could you try that to see if that works for you?

And yes, it fixed the issue! 💯 
@jeffkreeftmeijer thanks for the support.
