### ISSUE TITLE
Use LiveView hooks

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir-phoenix#37]
As reported in: https://github.com/appsignal/appsignal-elixir/pull/549#issuecomment-970407682
Article: https://sergiotapia.com/integrating-appsignal-with-phoenix-liveview-tutorial

**Comment by unflxw** [comment]
@jeffkreeftmeijer Am I wrong to think this was already done in https://github.com/appsignal/appsignal-elixir-phoenix/pull/46?

**Comment by jeffkreeftmeijer** [comment]
No, you're right. Closing!
