### ISSUE TITLE
Using appsignal_phoenix with phoenix 1.6.0

### ISSUE THREAD

**Issue by d-wire** [appsignal/appsignal-elixir-phoenix#42]
We're currently trying to upgrade our phoenix version to 1.6.0 due to another dependency requiring this, but we're getting
`appsignal_phoenix (versions 2.0.7 to 2.0.13) requires ~> 1.4`

Is it possible to add support for `Phoenix 1.6.0`?

**Comment by tombruijn** [comment]
Hi @d-wire, our version lock should allow Phoenix 1.6. The `~> 1.4` should allow versions 1.4 through anything below 2.0.

What versions of AppSignal and Phoenix have you specified in your mix.exs file? Can you share that?

**Comment by d-wire** [comment]
Hi @tombruijn. I have Phoenix specified as `{:phoenix, "~> 1.6.0"}` and Appsignal as `{:appsignal, "~> 2.2.10"}`.

**Comment by tombruijn** [comment]
When I tried to upgrade I saw a similar message, but with more packages that seemed to limit the upgrade:

```
Failed to use "phoenix" (versions 1.6.0 to 1.6.6) because
  appsignal_phoenix (version 2.0.13) requires ~> 1.4
  phoenix_live_reload (version 1.3.3) requires ~> 1.4
  phoenix_live_view (versions 0.15.0 to 0.15.7) requires ~> 1.5.7
  mix.exs specifies ~> 1.6.0


Failed to use "telemetry" (version 1.0.0) because
  ecto_sql (version 3.6.2) requires ~> 0.4.0
  phoenix (versions 1.6.0 to 1.6.6) requires ~> 0.4 or ~> 1.0
```

What doesn't translate in the output snippet above, is that some lines are colored in red. As if to indicate they are a problem. The lines that are not in red, are in green, as if to indicate they are not the problem. The AppSignal line is colored in green.

![image](https://user-images.githubusercontent.com/282402/159433439-068dfe65-1678-49dc-b6a7-802afa98183d.png)

What instead I needed to do, was update all the packages listed in red, like the `phoenix_live_view` package. I'm not sure of the best way, but I temporarily added them to my project's `mix.exs` file, selected the desired version, ran `mix deps.get` and it worked. (Running `mix deps.update phoenix_live_view` did not work for me.) This process may require a couple attempts, I ended up with this:

```elixir
  defp deps do
    [
      {:phoenix, "~> 1.6.0"},
      {:phoenix_ecto, "~> 4.1"},
      {:ecto_sql, "~> 3.4"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 3.1"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_dashboard, "~> 0.6"},
      {:phoenix_live_view, "~> 0.17.7"},
      {:telemetry_metrics, "~> 0.4"},
      {:telemetry_poller, "~> 0.4"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:appsignal, "~> 2.2.10"},
      {:appsignal_phoenix, "~> 2.0.13"}
    ]
  end
```

@d-wire let me know if this helps!

**Comment by tombruijn** [comment]
@d-wire did you manage to resolve the problem? If so, we can close the issue :)

**Comment by d-wire** [comment]
@tombruijn I sure did! Thanks for the help!

**Comment by tombruijn** [comment]
@d-wire great to hear!
