### ISSUE TITLE
ElixirLS crash

### ISSUE THREAD

**Issue by thephw** [appsignal/appsignal-elixir-phoenix#45]
Hey @luismiramirez 👋🏻 

First of all, thank you for all your work on the project. I was looking to get some background information on this commit here:
https://github.com/appsignal/appsignal-elixir-phoenix/commit/4057c7e199aa06e77d1b5064688451cebe9c20fb

We are using the Elixir language server plugin for VSCode and are running into issues with the language server crashing and misapplying formatting to our code. It seems to be related to the commit above that resolved a mime dependency issues for elixir 1.9

We fixed our issue temporarily by changing the language server to run with `MIX_ENV=dev`, but wanted to better understand the original underlying issue to see if we could PR an update that works with both the defaults for the language server and solves the original issue.

Would you be able to provide some context and perhaps steps to recreate the original issue?

**Comment by tombruijn** [comment]
Hi @thephw, Thanks for the issue! Can you provide us with the error message you're seeing? You can also send it to support@appsignal.com if you mention this issue.

The commit you linked is there to get a working build on older Elixir versions. Mime is a dependency of plug and we can't use mime > 1 on these older Elixir versions. For this reason we've added this specific version lock for our test environments.

**Comment by thephw** [comment]
So the error we're getting is below. 

```
Started ElixirLS v0.8.2
Elixir version: "1.13.4 (compiled with Erlang/OTP 24)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.10.4 and erlang 22
MIX_ENV: test
MIX_TARGET: 
[Warn  - 11:47:11 AM] ERROR! the application :mime has a different value set for key :types during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was set to: %{}
  * Runtime value was not set

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile mime --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag



11:47:11.460 [error] Task #PID<0.276.0> started from #PID<0.123.0> terminating
** (stop) "aborting boot"
    (elixir 1.13.4) Config.Provider.boot/2
Function: &:erlang.apply/2
    Args: [#Function<1.84261748/1 in Mix.Tasks.Compile.All.load_apps/3>, [mime: nil]]
```

**Comment by tombruijn** [comment]
I'm confused looking at this. Our mime dependency locks to version `~> 1.0` should only apply on Elixir version 1.9 and lower. Your app reports it's using 1.13.4. It should not hit that code to use mime 1.0. Which makes me think that commit is not related.

I don't know what could be causing this error. I found [this similar question on the Elixir forum](https://elixirforum.com/t/validating-compile-runtime-configuration/32373), which makes me think of this [change to compile_env](https://github.com/appsignal/appsignal-elixir-phoenix/commit/42b2cdd816b3b54627cd77bdb3a6e87b20d5d38f), but the issue seems to originate from the mime package: https://github.com/elixir-plug/mime/blob/7ae92c29c56dd825b15e1fc657ce30cfd29019fc/lib/mime.ex#L116

Have you customized the mime types in your own app's config for a specific environment?

**Comment by thephw** [comment]
So we are not customizing the mime types. By default I believe that ElixirLS compiles with MIX_ENV=test and this issue disappears if you override to MIX_ENV=dev

**Comment by thephw** [comment]
So it's happening inside the VSCode extension. Let me see if I can recreate in a demo app and record a short loom video on how to get at the output. On the road for the next many days but should be able to get back to it this upcoming week.

**Comment by tombruijn** [comment]
I'm closing this issue. Let us know by commenting if it still happens with how we can reproduce it.
