### ISSUE TITLE
Readme / Documentation relative to v2.3.0

### ISSUE THREAD

**Issue by mlineen** [appsignal/appsignal-elixir-phoenix#61]
Getting this warning:

```
warning: use Appsignal.Phoenix is deprecated. Since AppSignal for Phoenix 2.3.0, Phoenix instrumentation is up automatically. The `use Appsignal.Phoenix` line is no longer needed and should be removed from your app's endpoint file.
```

The README has outdated instructions: https://github.com/appsignal/appsignal-elixir-phoenix/blob/main/README.md?plain=1#L20-L29

**Comment by shairyar** [comment]
Hey @mlineen thanks for pointing that out. We will take a look and update it.
