### ISSUE TITLE
Failure on `[:phoenix, :router_dispatch, :exception]`

### ISSUE THREAD

**Issue by johantell** [appsignal/appsignal-elixir-phoenix#62]
Hi there, I've been experiencing some telemetry disconnections for the `[:phoenix, :router_dispatch, :exception]` (function clause error).

The problem source is a raised custom exception in a live view mount which trickles up and isn't matched properly.

My theory is that there has been some changes within plug on how the stack trace is being passed into the telemetry event and adding a third clause that matches on `stacktrace` instead of `stack` in `EventHandler` fully solves it for me:

```elixir
  def phoenix_router_dispatch_exception(
        _event,
        _measurements,
        %{reason: %Plug.Conn.WrapperError{conn: conn, reason: reason, stack: stack}},
        _config
      ) do
    add_error(@tracer.root_span(), conn, reason, stack)
  end

  def phoenix_router_dispatch_exception(
        _event,
        _measurements,
        %{conn: conn, reason: reason, stack: stack},
        _config
      ) do
    add_error(@tracer.root_span(), conn, reason, stack)
  end

  # Added clause
  def phoenix_router_dispatch_exception(
        _event,
        _measurements,
        %{conn: conn, reason: reason, stacktrace: stack},
        _config
      ) do
    add_error(@tracer.root_span(), conn, reason, stack)
  end
```

I'm not fully sure if receiving `stacktrace` over `stack` is unexpected or not but I thought I better share it

**Comment by jeffkreeftmeijer** [comment]
Hey @johantell, 

Looks like you’re right. I’ve checked the Phoenix source and it looks like it’s indeed `:stacktrace` in the telemetry metadata, as opposed to `:stack` in Plug’s wrapped errors. We’re reviewing a patch in https://github.com/appsignal/appsignal-elixir-phoenix/pull/63.

**Comment by johantell** [comment]
Thanks a lot @jeffkreeftmeijer! ❤️ 💙 💛 💚
