### ISSUE TITLE
Support Phoenix 1.7

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir-phoenix#64]
Phoenix 1.7 is out and it's breaking our build.

There's an issue with the Phoenix compiler breaking the build.

```
warning: the :phoenix compiler is no longer required in your mix.exs.
Please find the following line in your mix.exs and remove the :phoenix entry:
    compilers: [..., :phoenix, ...] ++ Mix.compilers(),
  (phoenix 1.7.0) lib/mix/tasks/compile.phoenix.ex:8: Mix.Tasks.Compile.Phoenix.run/1
  (mix 1.14.3) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
  (mix 1.14.3) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.14.3) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
  (mix 1.14.3) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
  (mix 1.14.3) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1
```

When removed here https://github.com/appsignal/appsignal-elixir-phoenix/blob/1abba3b0d84d162eec564ce7dadb1b0ff6979b27/mix.exs#L39, the test suite won't compile, because of an issue with Phoenix View.

From the [announcement blog post](https://www.phoenixframework.org/blog/phoenix-1.7-final-released):

> New applications (and the phx generators), remove Phoenix.View as a dependency in favor of a new Phoenix.Template dependency, which uses function components as the basis for all rendering in the framework.

## To do

- [ ] Add CI builds for Phoenix < 1.7 and >= 1.7
- [ ] Remove the Phoenix compiler for Phoenix 1.7 compilation
- [ ] Update the usage of Phoenix.View to Phoenix.Template in Phoenix 1.7

**Comment by jeffkreeftmeijer** [comment]
Closed by https://github.com/appsignal/appsignal-elixir-phoenix/pull/65.
