### ISSUE TITLE
phoenix_html 4.0 just got released

### ISSUE THREAD

**Issue by rubas** [appsignal/appsignal-elixir-phoenix#79]
This should be updated {:phoenix_html, "~> 2.11 or ~> 3.0", optional: true},

https://hexdocs.pm/phoenix_html/changelog.html

**Comment by unflxw** [comment]
Thanks for bringing this to our attention @rubas!

Taking a quick look at it, it is unclear to me why we have `phoenix_html` declared as a dependency at all. I'll see if it is possible to remove it or make it test-only.

**Comment by wkirschbaum** [comment]
@unflxw it seems to have been added to ensure tests still works, but my feel it might be unnecessary.  Here is a conservative PR to fix the above: https://github.com/appsignal/appsignal-elixir-phoenix/pull/81

**Comment by unflxw** [comment]
Released version 2.3.5 with the fix provided in #81 (thanks @wkirschbaum!)

Closing this for now.
