### ISSUE TITLE
Performance tab - Query.MyApp.Repo now treated as an event

### ISSUE THREAD

**Issue by JMurphyWeb** [appsignal/appsignal-elixir-phoenix#9]
Sorry I opened the original issue in the wrong repo:

https://github.com/appsignal/appsignal-elixir/issues/605

I am on the latest release 2.0.2 and am still seeing this

___

<img width="800" alt="Screenshot 2020-12-11 at 11 59 41" src="https://user-images.githubusercontent.com/12638261/101895894-70538b80-3ba8-11eb-8082-8128e6e582b4.png">

## Describe the bug

See screenshot.

Since upgrade to 2.0 I am seeing Ecto.Query in my slow events blowing the stats completely off.

**Comment by jeffkreeftmeijer** [comment]
Hey @JMurphyWeb,

The Ecto instrumentation is in the `:appsignal` library, which is a dependency of this one. If you upgrade that to the latest version (2.0.5) `mix deps.upgrade appsignal`, we should start ignoring unwrapped Ecto queries.

Could you try that to see if that resolves your issue?

**Comment by JMurphyWeb** [comment]
Hey @jeffkreeftmeijer, I'm using appsignal_phoenix library. I've updated to 2.0.3 and can see that the underlying appsignal package was upgraded:

```
Upgraded:
  appsignal 2.0.5 => 2.0.7
  appsignal_phoenix 2.0.2 => 2.0.3
  appsignal_plug 2.0.2 => 2.0.4
```

Anyway I can see that since my latest deploy the ecto instrumentation is no longer there 👍

**Comment by jeffkreeftmeijer** [comment]
Great! Thanks for getting back to me on this, @JMurphyWeb! 👍
