### ISSUE TITLE
Update to support LiveView 1.0.0-rc.0?

### ISSUE THREAD

**Issue by dfalling** [appsignal/appsignal-elixir-phoenix#91]
Currently AppSignal requires Phoenix LiveView 0.9.0. Are there any reasons this can't be expanded to support 1.0.0 as well?

> Because your app depends on appsignal_phoenix ~> 2.0 which depends on phoenix_live_view ~> 0.9, phoenix_live_view ~> 0.9 is required.
So, because your app depends on phoenix_live_view ~> 1.0.0-rc.0, version solving failed.
** (Mix) Hex dependency resolution failed

I'm aware I can force the dependency resolution, but would love to see this resolved before LiveView rolls over to 1.0.0.

Thanks!

**Comment by jeffkreeftmeijer** [comment]
Hey @dfalling,

Thanks for opening this issue, and thanks for wanting to try AppSignal with LiveView's release candidate! We'll add the 1.x version to the list of supported versions in an upcoming version of AppSignal for Phoenix, but would like to do some testing first to make sure everything works like we expect.

In the meantime, and if you'd like to help with that, you could run AppSignal with the release candidate by using the `:override` keyword in your live view dependency. If you do, please let us know if everything works for you. We'll do some testing ourselves, and we'll add the `~> 1.0` dependency when we're confident it won't brake customers' setups.
